from dev import Spravka

href = 'http://romul.gvc.oao.rzd:8080/SASStoredProcess/do?_program=/OCRVFoundation/AOM/Daily/SP/'
hreft = 'http://caesar.gvc.oao.rzd:8081/SASStoredProcess/do?_program=/OCRVFoundation/AOM/Daily/SP/'
# аналитические справки ЦОММ
ANALIT_SPRAVKI_COMM = {
    "ввод информации": (
        Spravka(name='справка по вводу информации операторами депо',
                url=href + 'statdocitog',
                url_test=hreft + 'statdocitog'),
        Spravka(name='статистика обработки документов маршрута машиниста',
                url=href + 'statdocmm&mode=0&eidepo1=-1&eidordepo1=-1&eidor1=0',
                url_test=hreft + 'statdocmm&mode=0&eidepo1=-1&eidordepo1=-1&eidor1=0'),
        Spravka(name='cтатистика необработанных документов ',
                url=href + 'stneobrmm&ei1=0&ei2=0&ei3=0',
                url_test=hreft + 'stneobrmm&ei1=0&ei2=0&ei3=0'),
        Spravka(name='статистика обработки документов эп, нэп, инв',
                url=href + 'statep&mode=0&eidepo1=-1&eidordepo1=-1&eidor1=0',
                url_test=hreft + 'statep&mode=0&eidepo1=-1&eidordepo1=-1&eidor1=0'),
        Spravka(name='принятые маршруты по видам движения ',
                url=href + 'pmpvd',
                url_test=hreft + 'pmpvd'),
        Spravka(name='качество ввода документов',
                url=href + 'qualMM&P_TYPEOUT=0',
                url_test=hreft + 'qualMM&P_TYPEOUT=0'),
        Spravka(name='задержки по времени обработки документов',
                url=href + 'stattimemm',
                url_test=hreft + 'stattimemm'),
        Spravka(name='история одного маршрута',
                url=href + 'stathistone',
                url_test=hreft + 'stathistone'),
        Spravka(name='пропущенные номера маршрутов',
                url=href + 'missed_routes&P_TYPEOUT=0',
                url_test=hreft + 'missed_routes&P_TYPEOUT=0'),
        Spravka(name='справка по корректировке паспортов локомотивов с шифром 7',
                url=href + 'statkorr7sys2&mode=0&eidepo1=-1&eidordepo1=-1&eidor1=0',
                url_test=hreft + 'statkorr7sys2&mode=0&eidepo1=-1&eidordepo1=-1&eidor1=0')
    ),
    "просмотр маршрутов": (
        Spravka(name='маршруты формы ту-3 и тху-3 ',
                url=href + 'tu3txu3&eidor=0&eidordepo=0&eidepo=0',
                url_test=hreft + 'tu3txu3&eidor=0&eidordepo=0&eidepo=0'),
        Spravka(name='cправка о переходных маршрутах',
                url=href + 'trans_way&eidor=0&eidordepo=0&eidepo=0',
                url_test=hreft + 'trans_way&eidor=0&eidordepo=0&eidepo=0'),
        Spravka(name='маршруты с замечаниями',
                url=href + 'roadswithremark&eidor=0&eidordepo=0&eidepo=0',
                url_test=hreft + 'roadswithremark&eidor=0&eidordepo=0&eidepo=0'),
        Spravka(name='реестр маршрутов',
                url=href + 'reestrM&ei1=0&ei2=0&ei3=0&rpt=0&kr=0',
                url_test=hreft + 'reestrM&ei1=0&ei2=0&ei3=0&rpt=0&kr=0'),
        Spravka(name='квитанции фму-24',
                url=href + 'SHOWFMU24',
                url_test=hreft + 'SHOWFMU24'),
        Spravka(name='документы этсо',
                url=href + 'DOCETSO&ei1=0&ei2=0&ei3=0&rpt=0',
                url_test=hreft + 'DOCETSO&ei1=0&ei2=0&ei3=0&rpt=0'),
    ),
    "цепочки с ремонтами цоту": (
        Spravka(name='история локомотива',
                url=href + 'istloc_all',
                url_test=hreft + 'istloc_all'),
        Spravka(name='история ремонтов и то',
                url=href + 'istrem',
                url_test=hreft + 'istrem'),
        Spravka(name='неэксплуатируемый парк',
                url=href + 'npark',
                url_test=hreft + 'npark'),
        Spravka(name='разрывы в цепочках по времени',
                url=href + 'razrtime',
                url_test=hreft + 'razrtime'),
        Spravka(name='разрывы в цепочках по топливу',
                url=href + 'razrtop',
                url_test=hreft + 'razrtop'),
        Spravka(name='случаи снятия контроля по топливным цепочкам',
                url=href + 'slsncontrsys2&mode=0&eidepo1=-1&eidordepo1=-1&eidor1=0',
                url_test=hreft + 'slsncontrsys2&mode=0&eidepo1=-1&eidordepo1=-1&eidor1=0'),
        Spravka(name='последнее состояние локомотива (секции)',
                url=href + 'stateloc',
                url_test=hreft + 'stateloc'),
    ),
    "цепочки состояний тпс": (
        Spravka(name='цепочка локомотива цоту+асоуп',
                url=href + 'locchainasoup&prkr=0&ei1=0&ei2=0&ei3=0',
                url_test=hreft + 'locchainasoup&prkr=0&ei1=0&ei2=0&ei3=0'),
        Spravka(name='Неэксплуатируемый парк по данным ЕСПУЛ',
                url=href + 'nparkESPUL&otch=0',
                url_test=hreft + 'nparkESPUL&otch=0'),
        Spravka(name='История ремонтов и ТО по данным ЕСПУЛ',
                url=href + 'istremESPUL&otch=0',
                url_test=hreft + 'istremESPUL&otch=0'),
        Spravka(name='Разрывы цепочек дислокации ТПС',
                url=href + 'brokenloc&rpt=0',
                url_test=hreft + 'brokenloc&rpt=0'),
        Spravka(name='Цепочка локомотива с данными ЕСПУЛ',
                url=href + 'lhc&otch=0',
                url_test=hreft + 'lhc&otch=0'),
    ),
    "использование тпс": (
        Spravka(name='Лицевой счет локомотива',
                url=href + 'lcl',
                url_test=hreft + 'lcl'),
        Spravka(name='Показатели использования локомотивов по поездоучасткам и направлениям',
                url=href + 'ilppin',
                url_test=hreft + 'ilppin'),
        Spravka(name='Ведомость двойной тяги/подталкивания',
                url=href + 'dvtyaga',
                url_test=hreft + 'dvtyaga'),
        Spravka(name='Одиночное следование',
                url=href + 'onefollow&ei1=0&ei2=0&ei3=0',
                url_test=hreft + 'onefollow&ei1=0&ei2=0&ei3=0'),
        Spravka(name='Простои локомотивов',
                url=href + 'prostloc',
                url_test=hreft + 'prostloc'),
        Spravka(name='нормообразующие показатели',
                url=href + 'NormPokaz',
                url_test=hreft + 'NormPokaz'),
        Spravka(name='Показатели работы локомотивов по нормоучасткам',
                url=href + 'LOK_NU',
                url_test=hreft + 'LOK_NU'),
        Spravka(name='Справка по объему выполненной работы',
                url=href + 'workdone',
                url_test=hreft + 'workdone'),
        Spravka(name='Справка о работе электровозов',
                url=href + 'electr',
                url_test=hreft + 'electr'),
        Spravka(name='Маневровая работа по станциям и вагонным депо',
                url=href + 'manhozrab&ei1=0&ei2=0&ei3=0',
                url_test=hreft + 'manhozrab&ei1=0&ei2=0&ei3=0'),
        Spravka(name='Измерители работы локомотивов',
                url=href + 'izm_rab_loc',
                url_test=hreft + 'izm_rab_loc'),
        Spravka(name='Основные показатели работы ТПС',
                url=href + 'to2_r4&P_TYPEOUT=0',
                url_test=hreft + 'to2_r4&P_TYPEOUT=0'),
        Spravka(name='Использование локомотивов по территории работы',
                url=href + 'ISP_LOK',
                url_test=hreft + 'ISP_LOK'),
        Spravka(name='Количество проведенных поездов',
                url=href + 'DEPTRAIN',
                url_test=hreft + 'DEPTRAIN'),
        Spravka(name='Учет нахождения локомотивов на территории Финляндии',
                url=href + 'FinLOK',
                url_test=hreft + 'FinLOK'),
        Spravka(name='Перевод на неплановый ремонт без выдачи в работу',
                url=href + 'REMAFTREM&ei1=0&ei2=0&ei3=0',
                url_test=hreft + 'REMAFTREM&ei1=0&ei2=0&ei3=0'),
        Spravka(name='Простои ТПС свыше 3-х часов после ремонтов',
                url=href + 'MMAFTREM&ei1=0&ei2=0&ei3=0',
                url_test=hreft + 'MMAFTREM&ei1=0&ei2=0&ei3=0'),
        Spravka(name='Тяжеловесные поезда',
                url=href + 'ttp&ei1=0&ei2=0&ei3=0&us=&rpt=0',
                url_test=hreft + 'ttp&ei1=0&ei2=0&ei3=0&us=&rpt=0'),
        Spravka(name='Показатели использования ТПС оперативного отчета ЦО-1/ЦО-5',
                url=href + 'POKAZ_OP_CO1&ei1=0&ei2=0&ei3=0&rpt=0',
                url_test=hreft + 'POKAZ_OP_CO1&ei1=0&ei2=0&ei3=0&rpt=0'),
        Spravka(name='Неотправленные поезда',
                url=href + 'unsent_trains',
                url_test=hreft + 'unsent_trains'),
        Spravka(name='Перечень маршрутов для формирования оперативных показателей',
                url=href + 'op_ind&otch=0',
                url_test=hreft + 'op_ind&otch=0'),
    ),
    "использование мвпс": (
        Spravka(name='Составность МВПС',
                url=href + 'sostsec&eidor=0&eidordepo=0&eidepo=0',
                url_test=hreft + 'sostsec&eidor=0&eidordepo=0&eidepo=0'),
        Spravka(name='Секции не участвующие в тяге',
                url=href + '',
                url_test=hreft + ''),
        Spravka(name='Кандидаты на ремонт',
                url=href + 'PROBEG_MVPS&ei1=0&ei2=0&ei3=0',
                url_test=hreft + 'PROBEG_MVPS&ei1=0&ei2=0&ei3=0'),
        Spravka(name='Пробеги от ремонтов МВПС',
                url=href + 'MVPS_PR&ei1=0&ei2=0&ei3=0&rpt=0',
                url_test=hreft + 'MVPS_PR&ei1=0&ei2=0&ei3=0&rpt=0'),
        Spravka(name='Ввод норм периодичности ТО и ремонта МВПС',
                url=href + 'NORM_REM_MVPS',
                url_test=hreft + 'NORM_REM_MVPS'),
        Spravka(name='Ввод пробегов от построки и ремонов МВПС',
                url=href + 'PR_POSTR&ei1=0&ei2=0&ei3=0&rpt=0',
                url_test=hreft + 'PR_POSTR&ei1=0&ei2=0&ei3=0&rpt=0'),
        Spravka(name='Показатель безотказной работы МВПС',
                url=href + 'PBR',
                url_test=hreft + 'PBR'),
        Spravka(name='Выдача МВПС в рейс',
                url=href + 'MVPS_RACE&ei1=0&ei2=0&ei3=0&rpt=0',
                url_test=hreft + 'MVPS_RACE&ei1=0&ei2=0&ei3=0&rpt=0'),
    ),
    "работа бригад": (
        Spravka(name='Лицевой счет работника',
                url=href + 'licschet&mode=0&eidepo1=-1&eidordepo1=-1&eidor1=0',
                url_test=hreft + 'licschet&mode=0&eidepo1=-1&eidordepo1=-1&eidor1=0'),
        Spravka(name='Вывесные таблицы',
                url=href + 'vtab&ei1=0&ei2= &ei3=',
                url_test=hreft + 'vtab&ei1=0&ei2= &ei3='),
        Spravka(name='Справка о следовании пассажирами',
                url=href + 'brpass&ei1=0&ei2= &ei3=',
                url_test=hreft + 'brpass&ei1=0&ei2= &ei3='),
        Spravka(name='Отправление бригад с раб.временем более 2ч',
                url=href + 'delay2&ei1=0&ei2= &ei3=',
                url_test=hreft + 'delay2&ei1=0&ei2= &ei3='),
        Spravka(name='Отправление бригад с раб.временем более 2ч, по станциям',
                url=href + 'delay2st',
                url_test=hreft + 'delay2st'),
        Spravka(name='Прибытие бригад с превышением накладного времени',
                url=href + 'peresidka&P_TYPEOUT=0',
                url_test=hreft + 'peresidka&P_TYPEOUT=0'),
        Spravka(name='Использование бригад на удаленных плечах обслуживания',
                url=href + '',
                url_test=hreft + ''),
        Spravka(name='Количество документов принятых к учету в УТО5-ВЦ',
                url=href + 'uto5_countmm&ei1=0&ei2=0&ei3=0',
                url_test=hreft + 'uto5_countmm&ei1=0&ei2=0&ei3=0'),
        Spravka(name='Аналитика в УТО-5',
                url=href + 'uto5n&ei1=0&ei2=0&ei3=0',
                url_test=hreft + 'uto5n&ei1=0&ei2=0&ei3=0'),
        Spravka(name='Анализ динамики нарушений (аналитика УТО5)',
                url=href + 'uto5n_stat&otch=0',
                url_test=hreft + 'uto5n_stat&otch=0'),
    ),
    "э-энергия и топливо": (
        Spravka(name='Cправка о расходе э/э-топлива по депо приписки бригад',
                url=href + 'topdepo&eidor=0&eidordepo=0&eidepo=0',
                url_test=hreft + 'topdepo&eidor=0&eidordepo=0&eidepo=0'),
        Spravka(name='Снятие ТЭР по акту',
                url=href + 'topakt&eidor=0&eidordepo=0&eidepo=0',
                url_test=hreft + 'topakt&eidor=0&eidordepo=0&eidepo=0'),
        Spravka(name='Анализ неисправности счётчиков',
                url=href + 'neisprsch&eidor=0&eidordepo=0&eidepo=0',
                url_test=hreft + 'neisprsch&eidor=0&eidordepo=0&eidepo=0'),
        Spravka(name='Остатки топлива на локомотивах (бух.)',
                url=href + 'restfuelb&ei1=0&ei2=0&ei3=0',
                url_test=hreft + 'restfuelb&ei1=0&ei2=0&ei3=0'),
        Spravka(name='Набор масла по локомотивам',
                url=href + 'naboroil&mode=0&eidepo1=-1&eidordepo1=-1&eidor1=0',
                url_test=hreft + 'naboroil&mode=0&eidepo1=-1&eidordepo1=-1&eidor1=0'),
        Spravka(name='Набор и снятие топлива бригадами депо',
                url=href + 'fueldump&mode=0&eidepo1=-1&eidordepo1=-1&eidor1=0',
                url_test=hreft + 'fueldump&mode=0&eidepo1=-1&eidordepo1=-1&eidor1=0'),
        Spravka(name='Расход ТЭР по видам ремонта и на прочие нужды депо',
                url=href + 'terremdepo&mode=0&eidepo1=-1&eidordepo1=-1&eidor1=0',
                url_test=hreft + 'terremdepo&mode=0&eidepo1=-1&eidordepo1=-1&eidor1=0'),
        Spravka(name='Расход ТЭР по видам ремонта по данным системы ЕСПУЛ',
                url=href + 'fuel_cost_repair_espul',
                url_test=hreft + 'fuel_cost_repair_espul'),
        Spravka(name='Показатели использования ТПС находящегося в ожидании работы с расходом ТЭР без локомотивных бригад',
                url=href + 'hot_simple&ei1=0&ei2=0&ei3=0',
                url_test=hreft + 'hot_simple&ei1=0&ei2=0&ei3=0'),
        Spravka(name='Расход топлива по номеру поезда',
                url=href + 'ToplOnTrain&ei1=0&ei2=0&ei3=0',
                url_test=hreft + 'ToplOnTrain&ei1=0&ei2=0&ei3=0'),
        Spravka(name='Расход ТЭР на администрациях',
                url=href + 'txo125a',
                url_test=hreft + 'txo125a'),
        Spravka(name='Маршруты с применением (без применения) рекуперации',
                url=href + 'recuper&P_TYPEOUT=0',
                url_test=hreft + 'recuper&P_TYPEOUT=0'),
        Spravka(name='Расход ТЭР по машинистам ',
                url=href + 'FUELMASH&ei1=0&ei2=0&ei3=0',
                url_test=hreft + 'FUELMASH&ei1=0&ei2=0&ei3=0'),
        Spravka(name='Расход ТЭР в ожидании ремонта более 12 часов',
                url=href + 'ter_serv&P_TYPEOUT=0',
                url_test=hreft + 'ter_serv&P_TYPEOUT=0'),
        Spravka(name='Расход ТЭР по секциям',
                url=href + 'sec_rash&ei1=0&ei2=0&ei3=0&rpt=0',
                url_test=hreft + 'sec_rash&ei1=0&ei2=0&ei3=0&rpt=0'),
    ),
    "заезды": (
        Spravka(name='Заезды бригад других администраций на ЖД России из сообщений 1753',
                url=href + 'tzaezd&ei1=0&ei2= &ei3=',
                url_test=hreft + 'tzaezd&ei1=0&ei2= &ei3='),
        Spravka(name='Ввод макетов 1752-1755',
                url=href + '',
                url_test=hreft + ''),
        Spravka(name='Исходящие сообщения 1754',
                url=href + '1754OUT',
                url_test=hreft + '1754OUT'),
        Spravka(name='Исходящие сообщения 1755',
                url=href + '1755OUT',
                url_test=hreft + '1755OUT'),
        Spravka(name='Входящие сообщения 1752-1755',
                url=href + 'STATRACE&ei1=0&ei2=0&ei3=0&rpt=0',
                url_test=hreft + 'STATRACE&ei1=0&ei2=0&ei3=0&rpt=0'),
    ),
    "пробежные нормы": (
        Spravka(name='Расчет времени в пути в грузовом движении',
                url=href + 'ROADREG&otch=0',
                url_test=hreft + 'ROADREG&otch=0'),
        Spravka(name='Справочник принадлежности поздоучастков бригадоучасткам',
                url=href + 'traindistrict&otch=0',
                url_test=hreft + 'traindistrict&otch=0'),
        Spravka(name='Просмотр пробежных норм',
                url=href + 'uto9_norms_view&rpt=0',
                url_test=hreft + 'uto9_norms_view&rpt=0'),
        Spravka(name='Ввод пробежных норм',
                url=href + 'probegnorma_input&reload=0',
                url_test=hreft + 'probegnorma_input&reload=0'),
    ),
    "ввод плановых показателей": (
        Spravka(name='Ввод планов ЦО-4',
                url=href + 'bprFormCO4&edit=0&fig_id=1139&prRef=3&dorcode=41',
                url_test=hreft + 'bprFormCO4&edit=0&fig_id=1139&prRef=3&dorcode=41'),
        Spravka(name='Ввод показателей по полигону Инская-Челябинск-Екатеринбург',
                url=href + 'bprFormManual&edit=0&fig_id=102&prRef=2',
                url_test=hreft + 'bprFormManual&edit=0&fig_id=102&prRef=2'),
        Spravka(name='Формирования комплекса специализированной отчетности для руководства ОАО "РЖД"',
                url=href + 'bprFormNSt&edit=1&fig_id=180&prRef=5&dorcode=41',
                url_test=hreft + 'bprFormNSt&edit=1&fig_id=180&prRef=5&dorcode=41'),
        Spravka(name='Отнесение ответственности за неплановый ремонт',
                url=href + 'bprFormRO&edit=0&fig_id=155&prRef=6&dorcode=41',
                url_test=hreft + 'bprFormRO&edit=0&fig_id=155&prRef=6&dorcode=41'),
        Spravka(name='Плановые показатели работы и расхода топливно-энергетических ресурсов на тягу поездов',
                url=href + 'nsiplan&edit=0',
                url_test=hreft + 'nsiplan&edit=0'),
        Spravka(name='Загрузка плановых показателей расхода ТЭР',
                url=href + 'pprt&ei1=0&ei2=0&ei3=0&us=&rpt=0',
                url_test=hreft + 'pprt&ei1=0&ei2=0&ei3=0&us=&rpt=0'),
    ),
    "нтэц": (),
    "аудит и анализ": (
        Spravka(name='анализ источников данных маршрута машиниста',
                url=href + 'TEXN_MM',
                url_test=hreft + 'TEXN_MM'),
        Spravka(name='задержки по времени обработки документов',
                url=href + 'stattimemm',
                url_test=hreft + 'stattimemm'),
        Spravka(name='показатели работы операторов цоту',
                url=href + 'statrabtsoty&otch=0',
                url_test=hreft + 'statrabtsoty&otch=0'),
        Spravka(name='маршруты с превышением скорости',
                url=href + 'speed_limit_over',
                url_test=hreft + 'speed_limit_over'),
        Spravka(name='ввод маршрутов машиниста с кодом замечания 3,6,38 ',
                url=href + 'remarkitog&rpt=0',
                url_test=hreft + 'remarkitog&rpt=0'),
        Spravka(name='детальные данные маршрута машиниста',
                url=href + 'MMDetailData&type_win=0',
                url_test=hreft + 'MMDetailData&type_win=0'),
        Spravka(name='сравнение скорректированных маршрутов',
                url=href + 'cmp_adj_rr&type_win=0',
                url_test=hreft + 'cmp_adj_rr&type_win=0'),
        Spravka(name='анализ разрывов в цепочках по топливу',
                url=href + 'forma_po_razr',
                url_test=hreft + 'forma_po_razr'),
        Spravka(name='количество учтенных документов в цо-1вц/цо-5вц',
                url=href + 'rec_docs_amount',
                url_test=hreft + 'rec_docs_amount'),
        Spravka(name='контроль разрывов цепочек по дислокации локомотивных бригад',
                url=href + 'razr_po_brig',
                url_test=hreft + 'razr_po_brig'),
        Spravka(name='случаи изменения нумерации поездов',
                url=href + 'WRCHTRNUM',
                url_test=hreft + 'WRCHTRNUM'),
        Spravka(name='качество ввода актов о хозяйственной работе',
                url=href + 'hz_miss&rpt=0',
                url_test=hreft + 'hz_miss&rpt=0'),
        Spravka(name='соответствие данных ту-3 / тху-3 и фму-24',
                url=href + 'FMUMM',
                url_test=hreft + 'FMUMM'),
        Spravka(name='анализ совпадений кол-ва топлива ту-3,тху-3 и фму-24',
                url=href + 'FMUMM_AN&ei1=0&ei2=0&ei3=0&report=0',
                url_test=hreft + 'FMUMM_AN&ei1=0&ei2=0&ei3=0&report=0'),
        Spravka(name='анализ отправления и прибытия поездов по станциям',
                url=href + 'ANALYZESTAN',
                url_test=hreft + 'ANALYZESTAN'),
        Spravka(name='анализ времени работы локомотивных бригад',
                url=href + 'audit12&rpt=0',
                url_test=hreft + 'audit12&rpt=0'),
        Spravka(name='справка об экономящих и пережигающих машинистах локомотивов',
                url=href + 'vt_audit&P_TYPEOUT=0',
                url_test=hreft + 'vt_audit&P_TYPEOUT=0'),
        Spravka(name='использование нумерации пересылки в ремонт без его проведения',
                url=href + 'inpvr&ei1=0&ei2=0&ei3=0&us=&rpt=0',
                url_test=hreft + 'inpvr&ei1=0&ei2=0&ei3=0&us=&rpt=0'),
        Spravka(name='маршруты машинистов, принятые к обработке с признаком "неисправный счетчик"',
                url=href + 'neisprsch_svod&otch=0',
                url_test=hreft + 'neisprsch_svod&otch=0'),
        Spravka(name='анализ совпадений количества топлива в эмм с цомм',
                url=href + 'EMMFUEL&ei1=0&ei2=0&ei3=0&rpt=0',
                url_test=hreft + 'EMMFUEL&ei1=0&ei2=0&ei3=0&rpt=0'),
        Spravka(name='анализ объективности технических норм, установленных для локомотивных бригад',
                url=href + 'aotn&ei1=0&ei2=0&ei3=0&us=&rpt=0',
                url_test=hreft + 'aotn&ei1=0&ei2=0&ei3=0&us=&rpt=0'),
        Spravka(name='анализ объективности расхода тэр по локомотивам',
                url=href + 'aort&ei1=0&ei2=0&ei3=0&us=&rpt=0',
                url_test=hreft + 'aort&ei1=0&ei2=0&ei3=0&us=&rpt=0'),
        Spravka(name='номерные данные о поездах, участвующих в расчете участковой скорости, с учетом движения по многопарковым станциям',
                url=href + 'nom_dann&P_TYPEOUT=0',
                url_test=hreft + 'nom_dann&P_TYPEOUT=0'),
        Spravka(name='сравнение подтвержденных и неподтвержденных эмм',
                url=href + 'compar_emm&P_TYPEOUT=0',
                url_test=hreft + 'compar_emm&P_TYPEOUT=0'),
        Spravka(name='перечень неподтверждённых эмм оперативного отчета цо-1',
                url=href + 'ufemm&otch=0',
                url_test=hreft + 'ufemm&otch=0'),
        Spravka(name='сравнение эмм с мм по периодам следования в ремонт',
                url=href + 'sled_v_rem_emm_vs_mm&ei1=0&ei2=0&ei3=0&rpt=0',
                url_test=hreft + 'sled_v_rem_emm_vs_mm&ei1=0&ei2=0&ei3=0&rpt=0'),
        Spravka(name='отчет о неприменении систем рекуперативного торможения в эксплуатации',
                url=href + 'bez_recup&ei1=0&ei2=0&ei3=0&rpt=0',
                url_test=hreft + 'bez_recup&ei1=0&ei2=0&ei3=0&rpt=0'),
        Spravka(name='мониторинг работы локомотивов в грузовом виде движения',
                url=href + '1HPF&ei1=0&ei2=0&ei3=0&rpt=0',
                url_test=hreft + '1HPF&ei1=0&ei2=0&ei3=0&rpt=0'),
        Spravka(name='длительно простаивающие локомотивы',
                url=href + 'lsl_list&rpt=0',
                url_test=hreft + 'lsl_list&rpt=0')
    )
}

