from dev import Spravka

href = 'http://romul.gvc.oao.rzd:8080/SASStoredProcess/do?_program=/OCRVFoundation/AOM/Daily/SP/'
hreft = 'http://romul.gvc.oao.rzd:8081/SASStoredProcess/do?_program=/OCRVFoundation/AOM/Daily/SP/'
# аналитические справки ЦОММ
ANALIT_SPRAVKI_COMM = {
    "ввод информации": (
        Spravka(name='справка по вводу информации операторами депо',
                url=href + 'statdocitog',
                url_test=hreft + 'statdocitog'),
        Spravka(name='статистика обработки документов маршрута машиниста',
                url=href + 'statdocmm&mode=0&eidepo1=-1&eidordepo1=-1&eidor1=0',
                url_test=hreft + 'statdocmm&mode=0&eidepo1=-1&eidordepo1=-1&eidor1=0'),
        Spravka(name='cтатистика необработанных документов ',
                url=href + 'stneobrmm&ei1=0&ei2=0&ei3=0',
                url_test=hreft + 'stneobrmm&ei1=0&ei2=0&ei3=0'),
        Spravka(name='статистика обработки документов эп, нэп, инв',
                url=href + 'statep&mode=0&eidepo1=-1&eidordepo1=-1&eidor1=0',
                url_test=hreft + 'statep&mode=0&eidepo1=-1&eidordepo1=-1&eidor1=0'),
        Spravka(name='принятые маршруты по видам движения ',
                url=href + 'pmpvd',
                url_test=hreft + 'pmpvd'),
        Spravka(name='качество ввода документов',
                url=href + 'qualMM&P_TYPEOUT=0',
                url_test=hreft + 'qualMM&P_TYPEOUT=0'),
        Spravka(name='задержки по времени обработки документов',
                url=href + 'stattimemm',
                url_test=hreft + 'stattimemm'),
        Spravka(name='история одного маршрута',
                url=href + 'stathistone',
                url_test=hreft + 'stathistone'),
        Spravka(name='пропущенные номера маршрутов',
                url=href + 'missed_routes&P_TYPEOUT=0',
                url_test=hreft + 'missed_routes&P_TYPEOUT=0'),
        Spravka(name='справка по корректировке паспортов локомотивов с шифром 7',
                url=href + 'statkorr7sys2&mode=0&eidepo1=-1&eidordepo1=-1&eidor1=0',
                url_test=hreft + 'statkorr7sys2&mode=0&eidepo1=-1&eidordepo1=-1&eidor1=0')
    ),
    "просмотр маршрутов": (),
    "цепочки с ремонтами цоту": (),
    "цепочки состояний тпс": (),
    "использование тпс": (),
    "использование мвпс": (),
    "работа бригад": (),
    "э-энергия и топливо": (),
    "заезды": (),
    "пробежные нормы": (),
    "ввод плановых показателей": (),
    "нтэц": (),
    "аудит и анализ": (
        Spravka(name='анализ источников данных маршрута машиниста',
                url=href + 'TEXN_MM',
                url_test=hreft + 'TEXN_MM'),
        Spravka(name='задержки по времени обработки документов',
                url=href + 'stattimemm',
                url_test=hreft + 'stattimemm'),
        Spravka(name='показатели работы операторов цоту',
                url=href + 'statrabtsoty&otch=0',
                url_test=hreft + 'statrabtsoty&otch=0'),
        Spravka(name='маршруты с превышением скорости',
                url=href + 'speed_limit_over',
                url_test=hreft + 'speed_limit_over'),
        Spravka(name='ввод маршрутов машиниста с кодом замечания 3,6,38 ',
                url=href + 'remarkitog&rpt=0',
                url_test=hreft + 'remarkitog&rpt=0'),
        Spravka(name='детальные данные маршрута машиниста',
                url=href + 'MMDetailData&type_win=0',
                url_test=hreft + 'MMDetailData&type_win=0'),
        Spravka(name='сравнение скорректированных маршрутов',
                url=href + 'cmp_adj_rr&type_win=0',
                url_test=hreft + 'cmp_adj_rr&type_win=0'),
        Spravka(name='анализ разрывов в цепочках по топливу',
                url=href + 'forma_po_razr',
                url_test=hreft + 'forma_po_razr'),
        Spravka(name='количество учтенных документов в цо-1вц/цо-5вц',
                url=href + 'rec_docs_amount',
                url_test=hreft + 'rec_docs_amount'),
        Spravka(name='контроль разрывов цепочек по дислокации локомотивных бригад',
                url=href + 'razr_po_brig',
                url_test=hreft + 'razr_po_brig'),
        Spravka(name='случаи изменения нумерации поездов',
                url=href + 'WRCHTRNUM',
                url_test=hreft + 'WRCHTRNUM'),
        Spravka(name='качество ввода актов о хозяйственной работе',
                url=href + 'hz_miss&rpt=0',
                url_test=hreft + 'hz_miss&rpt=0'),
        Spravka(name='соответствие данных ту-3 / тху-3 и фму-24',
                url=href + 'FMUMM',
                url_test=hreft + 'FMUMM'),
        Spravka(name='анализ совпадений кол-ва топлива ту-3,тху-3 и фму-24',
                url=href + 'FMUMM_AN&ei1=0&ei2=0&ei3=0&report=0',
                url_test=hreft + 'FMUMM_AN&ei1=0&ei2=0&ei3=0&report=0'),
        Spravka(name='анализ отправления и прибытия поездов по станциям',
                url=href + 'ANALYZESTAN',
                url_test=hreft + 'ANALYZESTAN'),
        Spravka(name='анализ времени работы локомотивных бригад',
                url=href + 'audit12&rpt=0',
                url_test=hreft + 'audit12&rpt=0'),
        Spravka(name='справка об экономящих и пережигающих машинистах локомотивов',
                url=href + 'vt_audit&P_TYPEOUT=0',
                url_test=hreft + 'vt_audit&P_TYPEOUT=0'),
        Spravka(name='использование нумерации пересылки в ремонт без его проведения',
                url=href + 'inpvr&ei1=0&ei2=0&ei3=0&us=&rpt=0',
                url_test=hreft + 'inpvr&ei1=0&ei2=0&ei3=0&us=&rpt=0'),
        Spravka(name='маршруты машинистов, принятые к обработке с признаком "неисправный счетчик"',
                url=href + 'neisprsch_svod&otch=0',
                url_test=hreft + 'neisprsch_svod&otch=0'),
        Spravka(name='анализ совпадений количества топлива в эмм с цомм',
                url=href + 'EMMFUEL&ei1=0&ei2=0&ei3=0&rpt=0',
                url_test=hreft + 'EMMFUEL&ei1=0&ei2=0&ei3=0&rpt=0'),
        Spravka(name='анализ объективности технических норм, установленных для локомотивных бригад',
                url=href + 'aotn&ei1=0&ei2=0&ei3=0&us=&rpt=0',
                url_test=hreft + 'aotn&ei1=0&ei2=0&ei3=0&us=&rpt=0'),
        Spravka(name='анализ объективности расхода тэр по локомотивам',
                url=href + 'aort&ei1=0&ei2=0&ei3=0&us=&rpt=0',
                url_test=hreft + 'aort&ei1=0&ei2=0&ei3=0&us=&rpt=0'),
        Spravka(name='номерные данные о поездах, участвующих в расчете участковой скорости, с учетом движения по многопарковым станциям',
                url=href + 'nom_dann&P_TYPEOUT=0',
                url_test=hreft + 'nom_dann&P_TYPEOUT=0'),
        Spravka(name='сравнение подтвержденных и неподтвержденных эмм',
                url=href + 'compar_emm&P_TYPEOUT=0',
                url_test=hreft + 'compar_emm&P_TYPEOUT=0'),
        Spravka(name='перечень неподтверждённых эмм оперативного отчета цо-1',
                url=href + 'ufemm&otch=0',
                url_test=hreft + 'ufemm&otch=0'),
        Spravka(name='сравнение эмм с мм по периодам следования в ремонт',
                url=href + 'sled_v_rem_emm_vs_mm&ei1=0&ei2=0&ei3=0&rpt=0',
                url_test=hreft + 'sled_v_rem_emm_vs_mm&ei1=0&ei2=0&ei3=0&rpt=0'),
        Spravka(name='отчет о неприменении систем рекуперативного торможения в эксплуатации',
                url=href + 'bez_recup&ei1=0&ei2=0&ei3=0&rpt=0',
                url_test=hreft + 'bez_recup&ei1=0&ei2=0&ei3=0&rpt=0'),
        Spravka(name='мониторинг работы локомотивов в грузовом виде движения',
                url=href + '1HPF&ei1=0&ei2=0&ei3=0&rpt=0',
                url_test=hreft + '1HPF&ei1=0&ei2=0&ei3=0&rpt=0'),
        Spravka(name='длительно простаивающие локомотивы',
                url=href + 'lsl_list&rpt=0',
                url_test=hreft + 'lsl_list&rpt=0')
    )
}

